
runtime: go112

instance_class: F2

env_variables:
  BUCKET_NAME: "sample-7777 filesample3"



handlers:

- url: /
  static_files: htmls/appri_start.html
  upload: htmls/appri_start.html

- url: /css/(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)

- url: /htmls/(.*\.html)
  static_files: htmls/\1
  upload: htmls/(.*\.html)

- url: /js/(.*\.js)
  static_files: js/\1
  upload: js/(.*\.js)

- url: /images/(.*\.png)
  static_files: images/\1
  upload: images/(.*\.png)

- url: /photo/(.*\.jpg)
  static_files: photo/\1
  upload: photo/(.*\.jpg)

- url: /audio/(.*\.*)
  static_files: audio/\1
  upload: audio/(.*\.*)

- url: /movie/(.*\.*)
  static_files: movie/\1
  upload: movie/(.*\.*)

- url: /.*
  script: auto



